# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GoreleaserPlayground < Formula
  desc "Goreleaser playground"
  homepage "https://github.com/andrew-farries/goreleaser-playground"
  version "0.2.4"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/andrew-farries/goreleaser-playground/releases/download/v0.2.4/goreleaser-playground_Darwin_arm64.tar.gz"
      sha256 "b2dacb1e37e071d853996f8b4ad15995b3f6b286bc114f1c9f548f47b2f1faff"

      def install
        bin.install "goreleaser-playground"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/andrew-farries/goreleaser-playground/releases/download/v0.2.4/goreleaser-playground_Darwin_x86_64.tar.gz"
      sha256 "18a66530e281a324037087f9f06eb7558c96998e118787d38987dde0bc207f7f"

      def install
        bin.install "goreleaser-playground"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/andrew-farries/goreleaser-playground/releases/download/v0.2.4/goreleaser-playground_Linux_x86_64.tar.gz"
      sha256 "da1a3ec9673b5fb72257eb801125c0020a5f89ac4290d31d14c04f815dd83c6e"

      def install
        bin.install "goreleaser-playground"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/andrew-farries/goreleaser-playground/releases/download/v0.2.4/goreleaser-playground_Linux_arm64.tar.gz"
      sha256 "7d2fea6c1c31eab687183f89ec5dcbe15b333d04724813f8bda6aff46fafd977"

      def install
        bin.install "goreleaser-playground"
      end
    end
  end
end
