# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GoreleaserPlayground < Formula
  desc "Goreleaser playground"
  homepage "https://github.com/andrew-farries/goreleaser-playground"
  version "0.2.3"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/andrew-farries/goreleaser-playground/releases/download/v0.2.3/goreleaser-playground_Darwin_arm64.tar.gz"
      sha256 "63b6b2b33bc429bb20141c491dd347eade08ee7826f197bc75611bfe9c458ecc"

      def install
        bin.install "goreleaser-playground"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/andrew-farries/goreleaser-playground/releases/download/v0.2.3/goreleaser-playground_Darwin_x86_64.tar.gz"
      sha256 "d0429f29254b38f6859cbb9956f38730dec5c76e4f385845ba36460722159ffc"

      def install
        bin.install "goreleaser-playground"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/andrew-farries/goreleaser-playground/releases/download/v0.2.3/goreleaser-playground_Linux_x86_64.tar.gz"
      sha256 "90e494357471e9d08135eb29d3e597aa2cc0344861bd63ec942065bf88e3fbcd"

      def install
        bin.install "goreleaser-playground"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/andrew-farries/goreleaser-playground/releases/download/v0.2.3/goreleaser-playground_Linux_arm64.tar.gz"
      sha256 "ccb1cf248d81812cc6bbaf960d6f770229393fdb1cd37e346e984361deae397f"

      def install
        bin.install "goreleaser-playground"
      end
    end
  end
end
